./svm_rank_learn RankMamba/Results/train_feature0.dat RankMamba/Results/model_0_mamba.dat
./svm_rank_learn RankMamba/Results/train_feature1.dat RankMamba/Results/model_1_mamba.dat
./svm_rank_learn RankMamba/Results/train_feature2.dat RankMamba/Results/model_2_mamba.dat
./svm_rank_learn RankMamba/Results/train_feature3.dat RankMamba/Results/model_3_mamba.dat
./svm_rank_learn RankMamba/Results/train_feature4.dat RankMamba/Results/model_4_mamba.dat
./svm_rank_classify RankMamba/Results/test_feature0.dat RankMamba/Results/model_0_mamba.dat
./svm_rank_classify RankMamba/Results/test_feature1.dat RankMamba/Results/model_1_mamba.dat
./svm_rank_classify RankMamba/Results/test_feature2.dat RankMamba/Results/model_2_mamba.dat
./svm_rank_classify RankMamba/Results/test_feature3.dat RankMamba/Results/model_3_mamba.dat
./svm_rank_classify RankMamba/Results/test_feature4.dat RankMamba/Results/model_4_mamba.dat