./svm_rank_learn -c 0.01 /Users/yuqi/Downloads/RankSVM_for_SLR/RankMamba/features/train_feature_modified0.dat /Users/yuqi/Downloads/RankSVM_for_SLR/RankMamba/features/model_0_mamba.dat
./svm_rank_learn -c 0.01 /Users/yuqi/Downloads/RankSVM_for_SLR/RankMamba/features/train_feature_modified1.dat /Users/yuqi/Downloads/RankSVM_for_SLR/RankMamba/features/model_1_mamba.dat
./svm_rank_learn -c 0.01 /Users/yuqi/Downloads/RankSVM_for_SLR/RankMamba/features/train_feature_modified2.dat /Users/yuqi/Downloads/RankSVM_for_SLR/RankMamba/features/model_2_mamba.dat
./svm_rank_learn -c 0.01 /Users/yuqi/Downloads/RankSVM_for_SLR/RankMamba/features/train_feature_modified3.dat /Users/yuqi/Downloads/RankSVM_for_SLR/RankMamba/features/model_3_mamba.dat
./svm_rank_learn -c 0.01 /Users/yuqi/Downloads/RankSVM_for_SLR/RankMamba/features/train_feature_modified4.dat /Users/yuqi/Downloads/RankSVM_for_SLR/RankMamba/features/model_4_mamba.dat
./svm_rank_classify /Users/yuqi/Downloads/RankSVM_for_SLR/RankMamba/features/test_feature_modified0.dat /Users/yuqi/Downloads/RankSVM_for_SLR/RankMamba/features/model_0_mamba.dat /Users/yuqi/Downloads/RankSVM_for_SLR/RankMamba/features/predictions_0.dat
./svm_rank_classify /Users/yuqi/Downloads/RankSVM_for_SLR/RankMamba/features/test_feature_modified1.dat /Users/yuqi/Downloads/RankSVM_for_SLR/RankMamba/features/model_1_mamba.dat /Users/yuqi/Downloads/RankSVM_for_SLR/RankMamba/features/predictions_1.dat
./svm_rank_classify /Users/yuqi/Downloads/RankSVM_for_SLR/RankMamba/features/test_feature_modified2.dat /Users/yuqi/Downloads/RankSVM_for_SLR/RankMamba/features/model_2_mamba.dat /Users/yuqi/Downloads/RankSVM_for_SLR/RankMamba/features/predictions_2.dat
./svm_rank_classify /Users/yuqi/Downloads/RankSVM_for_SLR/RankMamba/features/test_feature_modified3.dat /Users/yuqi/Downloads/RankSVM_for_SLR/RankMamba/features/model_3_mamba.dat /Users/yuqi/Downloads/RankSVM_for_SLR/RankMamba/features/predictions_3.dat
./svm_rank_classify /Users/yuqi/Downloads/RankSVM_for_SLR/RankMamba/features/test_feature_modified4.dat /Users/yuqi/Downloads/RankSVM_for_SLR/RankMamba/features/model_4_mamba.dat /Users/yuqi/Downloads/RankSVM_for_SLR/RankMamba/features/predictions_4.dat
